export const SORT_ALPHABETICAL_ASCENDING = 'SORT_ALPHABETICAL_ASCENDING'
export const SORT_CARBON_OUTPUT_DESCENDING = 'SORT_CARBON_OUTPUT_DESCENDING'
export const SORT_CARBON_OUTPUT_ASCENDING = 'SORT_CARBON_OUTPUT_ASCENDING'
export const SORT_WATER_USAGE_DESCENDING = 'SORT_WATER_USAGE_DESCENDING'
export const SORT_WATER_USAGE_ASCENDING = 'SORT_WATER_USAGE_ASCENDING'
export const FILTER = 'FILTER'

export function sortBy (sortType) {
  return {
    type: sortType
  }
}
